### ISSUE TITLE
different_analysis.R no file

### ISSUE THREAD

**Issue by ngutrinh** [Arvindiyer/iCTC_paper#1]
I would like to ask the file for this, in the data file provided not including this file: 
line 35: genes<-read.csv('data/cell_surface_marker.csv',sep = "\t",header = TRUE)
Could you upload the file for further checking?
Thank your

**Comment by Arvindiyer** [comment]
@ngutrinh Sorry for the delay. It's been a long time I have checked my Github account. I just checked and indeed that file is not available. Attached is the file. Hope it helps. If need any further assistance please free to contact me.
[cell_surface_marker.csv](https://github.com/Arvindiyer/iCTC_paper/files/7006954/cell_surface_marker.csv)

**Comment by ngutrinh** [comment]
> @ngutrinh Sorry for the delay. It's been a long time I have checked my Github account. I just checked and indeed that file is not available. Attached is the file. Hope it helps. If need any further assistance please free to contact me.
> [cell_surface_marker.csv](https://github.com/Arvindiyer/iCTC_paper/files/7006954/cell_surface_marker.csv)

Thank you so much @Arvindiyer. It's really helpful for me!
